In [1]:
import pandas as pd
import numpy as np
from pathlib import Path # Importar Path para manejar rutas de archivos

## Cargar datos

In [2]:
# definir la ruta del archivo CSV
RAW_DATA_PATH = Path("../data/raw/enero/Facturas")  # Ruta de la carpeta raw

#lista de archivos CSV en la carpeta raw
csv_files = list(RAW_DATA_PATH.glob("*.csv")) 
csv_files

# cargar el archivo CSV en un DataFrame de pandas

[PosixPath('../data/raw/enero/Facturas/d1_11_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_03_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_14_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_19_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/mercacentro_06_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_03_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_15_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/mercacentro_21_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_27_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/surtiplaza_09_enero.csv'),
 PosixPath('../data/raw/enero/Facturas/d1_21_enero.csv')]

In [3]:
file_path = csv_files[7]  # Seleccionar el primer archivo CSV
df = pd.read_csv(file_path)
df.head()

,Item,Descripcion,Cantidad,Unidad,Valor_Unitario,Total
0,1,LECHE MERCACENTRO LV S.DES 6x1000 ml,2,paq,22300,44600

### columnas de todos los dataframe

In [4]:
# iterar sobre los archivos CSV y cargar cada uno en un DataFrame de pandas
for file in csv_files:
    df_temp = pd.read_csv(file)
    print(file.name)
    print(df_temp.columns)
    print("------")

d1_11_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
d1_03_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
surtiplaza_14_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
surtiplaza_19_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
mercacentro_06_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
surtiplaza_03_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
d1_15_enero.csv
Index(['Ref', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
mercacentro_21_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
d1_27_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------
surtiplaza_09_enero.csv
Index(['Producto', 'Cantidad', 'Unidad', 'Precio'], dtype='str')
------
d1_21_enero.csv
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total'], dtype='str')
------

# Normalización de datos

In [5]:

# Definir una lista para almacenar los DataFrames
dfs = []

# Diccionario para mapear nombres de meses en español a números
meses = {
    "enero": 1,
    "febrero": 2,
    "marzo": 3,
    "abril": 4,
    "mayo": 5,
    "junio": 6,
    "julio": 7,
    "agosto": 8,
    "septiembre": 9,
    "octubre": 10,
    "noviembre": 11,
    "diciembre": 12
}

# Iterar sobre los archivos CSV, cargar cada uno en un DataFrame y agregar columnas adicionales

for file in csv_files:
    df_temp = pd.read_csv(file)
    
    tienda_name = file.stem # Obtener el nombre del archivo sin la extensión
    partes = tienda_name.split("_") # Dividir el nombre del archivo en partes
    
    tienda = partes[0] # Nombre de la tienda
    dia = int(partes[1]) # Día como entero
    mes_nombre = partes[2].lower() # Nombre del mes en minúsculas
    
    mes_num = meses[mes_nombre] # Convertir el nombre del mes a número usando el diccionario
    año = 2026

    # Crear fecha real
    fecha_completa = pd.Timestamp(year=año, month=mes_num, day=dia)

    # Agregar columnas
    df_temp["tienda"] = tienda
    df_temp["fecha"] = fecha_completa
    df_temp["mes"] = mes_num
    df_temp["año"] = año

    dfs.append(df_temp)
    print(df_temp.columns)  # Verificar que la nueva columna se haya agregado correctamente
    print("------")

Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------

Index(['Ref', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Precio', 'tienda', 'fecha', 'mes',
       'año'],
      dtype='str')
------
Index(['Item', 'Descripcion', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total',
       'tienda', 'fecha', 'mes', 'año'],
      dtype='str')
------

In [6]:
dfs[7].head()

,Item,Descripcion,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,1,LECHE MERCACENTRO LV S.DES 6x1000 ml,2,paq,22300,44600,mercacentro,2026-01-21,1,2026

### normalizar nombres de columnas

In [7]:
# normalizar nombres de columnas para que sean iguales en todos los DataFrames 
for df in dfs:
    df.rename(columns={
        "Precio": "Valor_Unitario",
        "Descripcion": "Producto",
    }, inplace=True)

dfs[6].head()

,Ref,Producto,Cantidad,Unidad,Valor_Unitario,Total,tienda,fecha,mes,año
0,1,Queso holandés,1,und,8300,8300,d1,2026-01-15,1,2026
1,2,Quesillo bloque,1,und,9990,9990,d1,2026-01-15,1,2026
2,3,Tomates enteros,1,und,4350,4350,d1,2026-01-15,1,2026
3,4,Topping mediano,2,und,4950,9900,d1,2026-01-15,1,2026
4,5,Chips de vegetales,2,und,2990,5980,d1,2026-01-15,1,2026

In [10]:
# Eliminar columnas innecesarias "Ref" y "Item" si existen en los DataFrames
for df in dfs:
    if "Ref" in df.columns:
        df.drop(columns=["Ref"], inplace=True)
    if "Item" in df.columns:
        df.drop(columns=["Item"], inplace=True)

for df in dfs:
    print(df.columns)  # Verificar que las columnas se hayan eliminado correctamente
    print("------")

Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'tienda', 'fecha',
       'mes', 'año'],
      dtype='str')
------
Index(['Producto', 'Cantidad', 'Unidad', 'Valor_Unitario', 'Total', 'tienda',
       'fecha', 'mes', 'año'],
      dtype='str')
------

In [9]:
COLUMNAS_FINALES = [
    "producto",
    "precio_unitario",
    "cantidad",
    "total",
    "tienda",
    "fecha",
    "categoria"
]